"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

export default function Home() {
  const router = useRouter();
  const [adminEmail, setAdminEmail] = useState("");

  return (
    <div className="flex flex-col min-h-screen items-center justify-center" style={{ background: "var(--bg)" }}>
      <div className="w-full max-w-md p-8 rounded-xl shadow-lg" style={{ background: "var(--surface)", border: "1px solid var(--border)" }}>
        <div className="flex items-center gap-3 mb-6">
          <img src="/logo.png" alt="Logo" className="w-12 h-12 rounded-lg object-contain" />
          <div>
            <h1 className="text-xl font-bold" style={{ color: "var(--text)" }}>Enquiry Capture O2D</h1>
            <p className="text-xs" style={{ color: "var(--text-muted)" }}>Flowchart Management System</p>
          </div>
        </div>

        <p className="text-sm mb-6" style={{ color: "var(--text-secondary)" }}>
          Welcome to the Enquiry Capture O2D system by Saraswat Engineering Services.
        </p>

        {/* Quick Admin Access */}
        <div className="mb-6 p-4 rounded-lg" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
          <h3 className="text-sm font-bold mb-3" style={{ color: "var(--text)" }}>Admin Access</h3>
          <p className="text-[11px] mb-3" style={{ color: "var(--text-muted)" }}>
            Enter admin email to access the dashboard directly (no password needed)
          </p>
          <div className="flex gap-2">
            <input
              type="email"
              value={adminEmail}
              onChange={(e) => setAdminEmail(e.target.value)}
              placeholder="Enter admin email"
              className="flex-1 px-3 py-2.5 rounded-lg text-sm outline-none"
              style={{ background: "var(--surface)", border: "1px solid var(--border)", color: "var(--text)" }}
              onKeyDown={(e) => {
                if (e.key === "Enter" && adminEmail.trim()) {
                  router.push(`/admin?email=${encodeURIComponent(adminEmail.trim())}`);
                }
              }}
            />
            <button
              onClick={() => {
                if (adminEmail.trim()) {
                  router.push(`/admin?email=${encodeURIComponent(adminEmail.trim())}`);
                }
              }}
              className="px-4 py-2.5 rounded-lg text-sm font-semibold text-white"
              style={{ background: "var(--primary)" }}
            >
              Go
            </button>
          </div>
        </div>

        {/* Info */}
        <div className="space-y-3">
          <div className="p-3 rounded-lg" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
            <h4 className="text-xs font-bold mb-1" style={{ color: "var(--text)" }}>👤 User Access</h4>
            <p className="text-[11px]" style={{ color: "var(--text-muted)" }}>
              Users access the system via links generated by admin. The link format is: <code className="text-[10px] px-1 py-0.5 rounded" style={{ background: "var(--surface-3)" }}>/user?email=user@email.com</code>
            </p>
          </div>
          <div className="p-3 rounded-lg" style={{ background: "var(--surface-2)", border: "1px solid var(--border)" }}>
            <h4 className="text-xs font-bold mb-1" style={{ color: "var(--text)" }}>🔧 Setup</h4>
            <p className="text-[11px]" style={{ color: "var(--text-muted)" }}>
              First time? Add your email as admin in the Google Sheet Users tab with Is_Admin = TRUE, then access the admin panel above.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
